name: modernarabert
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.18
  - pip
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - pytorch>=2.0.0
  - pytorch-cuda=11.8  # Adjust based on your CUDA version
  - pip:
    - transformers>=4.35.0
    - datasets>=2.14.0
    - accelerate>=0.24.0
    - tokenizers>=0.15.0
    - farasa>=0.0.14
    - tqdm>=4.65.0
    - psutil>=5.9.0
    - gdown>=4.7.1
    - rarfile>=4.0
    - PyYAML>=6.0
    - openpyxl>=3.1.0
    - pytest>=7.4.0
    - black>=23.0.0
    - isort>=5.12.0

